# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'


# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['ryanoasis/vim-devicons']
hook_add='''
nnoremap <silent> <Leader>e :NERDTreeToggle<CR>
'''
